#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/pitch.h"
#include "images/start.h"
#include "images/ball.h"
#include "images/wall.h"
#include "images/dubs.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
  START2,
  PLAY2
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  char time[10];
  struct Positions pos;
  int direction = 1;
  int draw = 1;
  pos.titlex = 80;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      state = START;
      draw = 1;
      pos.titlex = 80;
      direction = 1;
    }
    waitForVBlank();

    switch (state) {
      case START:
        if (draw) {
          drawFullScreenImageDMA(start);
          drawCenteredString(30, 0, WIDTH, 8, "Press 'ENTER' to start!", WHITE);
          draw = 0;
        }
        undrawImageDMA(10, pos.titlex, 54, 7, start);
        if (pos.titlex <= 0 || pos.titlex + 54 >= WIDTH) {
          direction *= -1;
        }
        pos.titlex += direction;
        drawString(10, pos.titlex, "FREEKICKS", WHITE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
          vBlankCounter = 0;
          pos.ballx = 10;
          pos.bally = 100;
          pos.wallx = 80;
          pos.wally = 60;
          draw = 1;
        }
        // state = ?
        break;
      case PLAY:
        if (draw) {
          fillScreenDMA(GREEN);
          drawImageDMA(pos.wally, pos.wallx, WALL_WIDTH, WALL_HEIGHT, wall);
          drawRectDMA(50, 230, 10, 60, WHITE);
          draw = 0;
        }
        drawRectDMA(10, 10, 18, 8, GREEN);
        snprintf(time, 10, "%d", vBlankCounter / 60);
        drawString(10, 10, time, WHITE);
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx + BALL_WIDTH - 1, 1, BALL_HEIGHT, GREEN);
          pos.ballx--;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx, 1, BALL_HEIGHT, GREEN);
          pos.ballx++;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          drawRectDMA(pos.bally + BALL_HEIGHT - 1, pos.ballx, BALL_WIDTH, 1, GREEN);
          pos.bally--;
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx, BALL_WIDTH, 1, GREEN);
          pos.bally++;
        }
        if (pos.ballx + BALL_WIDTH >= pos.wallx && pos.ballx <= pos.wallx + WALL_WIDTH && pos.bally + BALL_HEIGHT >= pos.wally && pos.bally <= pos.wally + WALL_HEIGHT) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx + BALL_WIDTH >= WIDTH && (pos.bally > 110 || pos.bally < 50)) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx <= 0 || pos.bally <= 0 || pos.bally + BALL_HEIGHT >= 160) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx + BALL_WIDTH >= 230 && pos.bally <= 110 && pos.bally + BALL_HEIGHT >= 50) {
          state = START2;
          draw = 1;
        }
        drawImageDMA(pos.bally, pos.ballx, BALL_WIDTH, BALL_HEIGHT, ball);
        // state = ?
        break;
      case START2:
        if (draw) {
          fillScreenDMA(BLUE);
          drawCenteredString(10, 0, WIDTH, 8, "GET READY FOR LEVEL 2!", WHITE);
          drawCenteredString(30, 0, WIDTH, 8, "press 'ENTER' to start", WHITE);
          drawCenteredString(50, 0, WIDTH, 8, "press 'BACKSPACE' for main menu", WHITE);
          draw = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY2;
          vBlankCounter = 0;
          pos.ballx = 10;
          pos.bally = 100;
          pos.wallx = 80;
          pos.wally = 60;
          direction = 1;
          draw = 1;
        }
        break;
      case PLAY2:
        if (draw) {
          fillScreenDMA(GREEN);
          drawRectDMA(50, 230, 10, 60, WHITE);
          draw = 0;
        }
        if (pos.wally + WALL_HEIGHT >= 160 || pos.wally <= 0) {
          direction *= -1;
        }
        if (direction == 1) {
          drawRectDMA(pos.wally, pos.wallx, WALL_WIDTH, 1, GREEN);
        } else {
          drawRectDMA(pos.wally + WALL_HEIGHT - 1, pos.wallx, WALL_WIDTH, 1, GREEN);
        }
        pos.wally += direction;
        drawImageDMA(pos.wally, pos.wallx, WALL_WIDTH, WALL_HEIGHT, wall);
        drawRectDMA(10, 10, 18, 8, GREEN);
        snprintf(time, 10, "%d", vBlankCounter / 60);
        drawString(10, 10, time, WHITE);
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx + BALL_WIDTH - 1, 1, BALL_HEIGHT, GREEN);
          pos.ballx--;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx, 1, BALL_HEIGHT, GREEN);
          pos.ballx++;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          drawRectDMA(pos.bally + BALL_HEIGHT - 1, pos.ballx, BALL_WIDTH, 1, GREEN);
          pos.bally--;
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          drawRectDMA(pos.bally, pos.ballx, BALL_WIDTH, 1, GREEN);
          pos.bally++;
        }
        if (pos.ballx + BALL_WIDTH >= pos.wallx && pos.ballx <= pos.wallx + WALL_WIDTH && pos.bally + BALL_HEIGHT >= pos.wally && pos.bally <= pos.wally + WALL_HEIGHT) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx + BALL_WIDTH >= WIDTH && (pos.bally > 110 || pos.bally < 50)) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx <= 0 || pos.bally <= 0 || pos.bally + BALL_HEIGHT >= 160) {
          state = LOSE;
          draw = 1;
        }
        if (pos.ballx + BALL_WIDTH >= 230 && pos.bally <= 110 && pos.bally + BALL_HEIGHT >= 50) {
          state = WIN;
          draw = 1;
        }
        drawImageDMA(pos.bally, pos.ballx, BALL_WIDTH, BALL_HEIGHT, ball);
        // state = ?
        break;
      case WIN:
        if (draw) {
          drawFullScreenImageDMA(dubs);
          drawCenteredString(50, 0, WIDTH, 8, "YOU WIN!", WHITE);
          drawCenteredString(70, 0, WIDTH, 8, "press 'BACKSPACE' for main menu", WHITE);
          draw = 0;
        }
        
        // state = ?
        break;
      case LOSE:
        if (draw) {
          fillScreenDMA(RED);
          drawCenteredString(10, 0, WIDTH, 8, "YOU LOSE!", WHITE);
          drawCenteredString(30, 0, WIDTH, 8, "press 'BACKSPACE' for main menu", WHITE);
          draw = 0;
        }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
